apiVersion: apps/v1
## Revisit this being a StatefulSet because https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#deployments_vs_statefulsets
kind: Deployment
metadata:
  name: bitcoind
  labels:
    app: bitcoind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoind
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      containers:
      - name: bitcoind
        image: inanimate/bitcoin-core:0.1.0
        args: ["-conf=/app/bitcoin-core/bitcoin.conf"]
        volumeMounts:
          - name: bitcoin.conf
            mountPath: /app/bitcoin-core
          - name: block-storage
            mountPath: /app/bitcoin-core/block-storage
        imagePullPolicy: Always
        ports:
        - containerPort: 8332
          name: rpc
        - containerPort: 8333
          name: incoming
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "768Mi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 8333
          initialDelaySeconds: 25
          periodSeconds: 20
      volumes:
      - name: bitcoin.conf
        configMap:
          name: bitcoind-config
      - name: block-storage
        ## From https://kubernetes.io/docs/concepts/storage/volumes/#gce-create-persistent-disk
        gcePersistentDisk:
          pdName: bitcoin-block-storage
          fsType: ext4
