## From https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#dynamic_provisioning
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-block-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi